export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";

export const SET_CHANNELS = "SET_CHANNELS";
export const CREATE_CHANNEL = "CREATE_CHANNEL";

export const SET_CHANNEL_DETAIL = "SET_CHANNEL_DETAIL";
