export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";

export const GET_ALL_CHANNELS = "GET_ALL_CHANNELS";
export const POST_CHANNEL = "POST_CHANNEL";

export const GET_CHANNEL = "GET_CHANNEL";